// <auto-generated />
using System;
using AppTareasPorHacer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppTareasPorHacer.Migrations
{
    [DbContext(typeof(TareasContext))]
    partial class TareasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppTareasPorHacer.Models.Categoria", b =>
                {
                    b.Property<string>("CategoriaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoriaNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria");

                    b.HasData(
                        new
                        {
                            CategoriaId = "hogar",
                            CategoriaNombre = "Hogar"
                        },
                        new
                        {
                            CategoriaId = "trabajo",
                            CategoriaNombre = "Trabajo"
                        },
                        new
                        {
                            CategoriaId = "estudio",
                            CategoriaNombre = "Estudio"
                        },
                        new
                        {
                            CategoriaId = "ocio",
                            CategoriaNombre = "Ocio"
                        });
                });

            modelBuilder.Entity("AppTareasPorHacer.Models.Estado", b =>
                {
                    b.Property<string>("EstadoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EstadoNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstadoId");

                    b.ToTable("Estado");

                    b.HasData(
                        new
                        {
                            EstadoId = "pendiente",
                            EstadoNombre = "Pendiente"
                        },
                        new
                        {
                            EstadoId = "completada",
                            EstadoNombre = "Completada"
                        });
                });

            modelBuilder.Entity("AppTareasPorHacer.Models.Tarea", b =>
                {
                    b.Property<int>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TareaId"));

                    b.Property<string>("CategoriaFK")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoFK")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaTarea")
                        .HasColumnType("datetime2");

                    b.HasKey("TareaId");

                    b.HasIndex("CategoriaFK");

                    b.HasIndex("EstadoFK");

                    b.ToTable("Tarea");
                });

            modelBuilder.Entity("AppTareasPorHacer.Models.Tarea", b =>
                {
                    b.HasOne("AppTareasPorHacer.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppTareasPorHacer.Models.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Estado");
                });
#pragma warning restore 612, 618
        }
    }
}
